body:
  - attributes:
      description: Before you write something like “my web page goes blank” or “there is a content encoding error message appears in my browser”, make sure that you have done all of these tasks.
      label: Ensure that your issue is possible to solve by doing these tasks
      options:
        - label: I am using application packages whose source code is not optimized for production (source code is not minified).
          required: true
        - label: I have activated the test mode by changing the `TEST` constant value to `true` in the `.\index.php` file.
          required: true
        - label: I have made sure that there are files named `error` or `error-x` or `error-y` in the `.\engine\log` folder.
          required: true
    type: checkboxes
  - attributes:
      description: Also tell me, what did you expect to happen?
      label: Describe your issue in the field below
      placeholder: Your problems and expectations.
    type: textarea
    validations:
      required: true
  - attributes:
      description: What version of the package are you running?
      label: Package version
      options:
        - Development version (package on the `main` branch)
        - Stable release version (package with semantic version label such as `v1.0.0`)
        - Unstable release version (package with semantic version label but marked as a version release that isn’t ready for production)
    type: dropdown
    validations:
      required: true
  - attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Edge
        - Firefox
        - Safari
        - Others
    type: dropdown
  - attributes:
      description: Copy the log output that appears in the `.\engine\log\error` file then paste it there. Please copy the log lines with the most recent date only.
      label: Error logs of the core application if any
      render: shell
    type: textarea
  - attributes:
      description: Copy the log output that appears in the `.\engine\log\error-x` file then paste it there. Please copy the log lines with the most recent date only.
      label: Error log of the extension if any
      render: shell
    type: textarea
  - attributes:
      description: Copy the log output that appears in the `.\engine\log\error-y` file then paste it there. Please copy the log lines with the most recent date only.
      label: Error log of the layout if any
      render: shell
    type: textarea
  - attributes:
      description: Copy the log output that appears in the `.\error_log` file then paste it there. Please copy the log lines with the most recent date only.
      label: General error logs if any (if the application fails to set a custom error log path, then the error log will usually appear in this location)
      render: shell
    type: textarea
description: There must be something wrong and it really bothers you.
labels: [bug, choked]
name: Bug Report
