blank_issues_enabled: true
contact_links:
  - about: Learn more.
    name: Documentations
    url: https://mecha-cms.com/reference/1
  - about: Feature as a service.
    name: Feature Request
    url: https://github.com/mecha-cms/bounty/issues/new?template=request.yml
  - about: You really need my help regarding this application, urgently!
    name: Help Wanted
    url: https://github.com/orgs/mecha-cms/discussions/new?category=q-a